baseURL = 'https://aubrey-mcfate.github.io'
languageCode = 'en-us'
title = 'Aubrey McFate'
theme = 'hugo-book'
[params]
    BookFavicon = '/assets/favicon.png'
    BookLogo = '/assets/logo.svg'
    BookTheme = 'auto'
[caches]
  [caches.images]
    dir = ':cacheDir/images'    
    

